# Use an official Node runtime as the base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install project dependencies
RUN npm install

EXPOSE 5173

# Build the React app
# CMD [ "pnpm" , "run" , "dev" ]
CMD ["npm","run","dev"]