version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: ./docker/docker-development/Dockerfile.dev

    ports:
      - '3000:5173'

    volumes:
      - /app/node_modules
      - ../../:/app
