FROM node:20-alpine AS build

RUN npm i -g pnpm
WORKDIR /app

COPY package.json ./
RUN pnpm install

COPY . .

RUN pnpm run build

FROM node:20-alpine AS runtime

WORKDIR /app

COPY --from=build /app/build ./build
COPY package.json package-lock.json ./
RUN npm install --production

ENV APP_NAME=vitrin

CMD ["pnpm", "run", "start"]